project_id = "bruh"

[functions.feed]
verify_jwt = false

[functions.ingest-x-posts]
verify_jwt = false

[functions.ingest-xhs-posts]
verify_jwt = false

[functions.build-feed]
verify_jwt = false

[functions.generate-message]
verify_jwt = false

[functions.generate-post-interactions]
verify_jwt = false

[functions.ingest-top-news]
verify_jwt = false

[functions.build-news-events]
verify_jwt = false

[functions.message-starters]
verify_jwt = false
